# Generated by Django 4.1.5 on 2023-05-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressmeter', '0002_alter_activity_options_rename_reason_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
