# Generated by Django 4.1.5 on 2023-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField(verbose_name='Date of Transaction')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('statement', models.CharField(choices=[('expenses', 'Expenses'), ('income', 'Income'), ('saving', 'Savings')], default='expenses', max_length=10, verbose_name='Statement')),
            ],
        ),
    ]
