# Generated by Django 4.1.5 on 2023-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financesheet',
            name='statement',
            field=models.CharField(choices=[('expenses', 'Expenses'), ('income', 'Income'), ('savings', 'Savings')], default='expenses', max_length=10, verbose_name='Statement'),
        ),
    ]
