# Generated by Django 4.1.5 on 2023-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(verbose_name='Date & Time')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(default='N/A', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
